import Head from "next/head";
import { useState } from "react";
import About from "../components/about";
import Contact from "../components/contact/contact";
import Footer from "../components/footer";
import Initial from "../components/initial";
import Modal from "../components/modal";
import Tasks from "../components/tasks";
import { getContact, getTasks } from "../fakeApi/data";
import { ContactDetails } from "../types/contactDetails";
import { Task } from "../types/task";

interface Props {
  tasks: Task[];
  contactDetails: ContactDetails;
}
const Home = ({ tasks, contactDetails }: Props) => {
  const [isOpenedModal, setIsOpenedModal] = useState(false);

  return (
    <div>
      <Head>
        <title>Bam Traslochi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal
        phoneNumber={contactDetails.Telefono}
        isOpen={isOpenedModal}
        closeModal={() => setIsOpenedModal(false)}
      />

      {/* <FontAwesomeIcon
        icon={faArrowCircleDown}
        className="w-8 h-fit mt-auto animate-ping z-10 absolute pointer-events-none right-40 bottom-10"
      /> */}

      <Initial openModal={() => setIsOpenedModal(true)} />
      <Tasks tasks={tasks} />
      <About />
      <Contact details={contactDetails} />
      <Footer />
    </div>
  );
};

export async function getStaticProps() {
  const tasks = getTasks();
  const contactDetails = getContact();

  return {
    props: { tasks, contactDetails },
  };
}

export default Home;
